drop table "user" cascade;
drop table "roles" cascade;
drop table "provincias" cascade;
drop table "municipios" cascade;
drop table "paises" cascade;
drop table "lineas_pedido" cascade;
drop table "pedidos" cascade;
drop table "servicios" cascade;
drop table "migration" cascade;
drop table "gender" cascade;
drop table "profile" cascade;
drop table "status" cascade;
drop table "user_type" cascade;
drop table "etiquetas" cascade;
drop table "imagen_profile" cascade;
drop table "lineas_venta" cascade;
drop table "servicios_etiquetas" cascade;
drop table "ventas";
