drop table "user" cascade;
drop table "roles" cascade;
drop table "provincias" cascade;
drop table "municipios" cascade;
drop table "paises" cascade;
drop table "tipos_iva" cascade;
drop table "servicios" cascade;
drop table "imagen_servicio";
drop table "migration" cascade;
drop table "gender" cascade;
drop table "profile" cascade;
drop table "status" cascade;
drop table "user_type" cascade;
drop table "imagen_profile" cascade;
drop table "lineas_venta" cascade;
drop table "etiquetas" cascade;
drop table "servicios_etiquetas" cascade;
drop table "categorias" cascade;
drop table "servicios_categorias" cascade;
drop table "ventas";
drop table "estado_ventas";
drop table "unidades_tiempo";
drop table "comentarios";
drop table "votaciones";

delete from "user";
delete from "roles";
delete from "provincias";
delete from "municipios";
delete from  "paises";
delete from   "tipos_iva";
delete from   "servicios";
delete from   "imagen_servicio";
delete from   "gender";
delete from   "profile";
delete from   "status";
delete from   "user_type";
delete from   "imagen_profile";
delete from   "lineas_venta";
delete from   "etiquetas";
delete from   "servicios_etiquetas";
delete from   "categorias";
delete from   "servicios_categorias";
delete from   "ventas";
delete from   "estado_ventas";
delete from   "unidades_tiempo";
delete from   "comentarios";
delete from   "votaciones";
