<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Municipios' => '',
    'Nombre Municipio' => '',
    'Nombre Pais' => '',
    'Nombre Provincia' => '',
    'Pais' => '',
    'Provincia ID' => '',
    'Provincias' => '',
    'Rol' => '',
    'Roles' => '',
    'Status' => '',
    'These are easy to manage via UI. Just click the link below to manage profiles.' => 'Son fáciles de gestionar con nuestra UI. Sólo haz clic para administrar perfiles',
    'This is the place to get it done.' => 'Este es el sitio para hacerlo',
    'This is the place to manage users.' => 'Este es el sitio para gestionar tus usuarios',
    'This is where you manage Roles.' => 'Desde aquí podrás gestionar los Roles',
    'This is where you manage Statutes.' => 'Aquí es donde administrarás los estados',
    'Update' => 'Actualizar',
    'Update Profile: ' => 'Actualizar Perfil',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'User' => 'Usuario',
    'User Type' => 'Tipo de Usuario',
    'User Types' => 'Tipos de Usuario',
    'Users' => 'Usuarios',
    'Welcome to Administrator\'s Zone' => 'Zona de administración',
    'You can add a new role if you like, just click the link below to get started.' => 'Puedes añadir nuevos roles, haz clic en el enlace.',
    'You can add a new status if you like, just click the link below to get started.' => 'Puedes añadir un nuevo estutus, haz clic en el enlace.',
    'You can add or delete.' => 'Puedes añadir o eliminar',
    'You can decide who is admin and who is not.' => 'Puedes decidir quién es Administrador y quién no.',
    'You can edit status and roles from here.' => 'Puedes editar status y roles desde aquí.',
    'You can edit user types from here.' => 'Puedes gestionar los tipos de usuario desde aquí.',
    'You can manage users, roles and more with theese tools' => 'Puedes gestionar usuarios, roles y mucho más desde esta página',
    'Desc Pais' => '@@@@',
    'Desc Provincia' => '@@@@',
    'Administrator\'s Zone' => 'Zona de administración',
    'Are you sure you want to delete this item?' => '¿Está seguro  que desea borrar este item?',
    'Are you sure you want to delete this user?' => '¿Está seguro que desea borrar este usuario?',
    'Create' => 'Crear',
    'Create Municipio' => 'Crear Municipio',
    'Create Pais' => 'Crear País',
    'Create Profile' => 'Crear Perfil',
    'Create Provincia' => 'Crear Provincia',
    'Create Rol' => 'Crear Rol',
    'Create Status' => 'Crear Status',
    'Create User' => 'Crear Usuario',
    'Create User Type' => 'Crear tipo de usuario',
    'Delete' => 'Borrar',
    'Den Rol' => 'Rol',
    'Gender' => 'Género',
    'ID' => 'ID',
    'Login' => 'Login',
    'Need to review Profiles?' => '¿Necesita revisar Perfiles?',
    'Please fill out the following fields to login:' => 'Por favor rellene los siguientes campos para entrar',
    'Profile' => 'Perfil',
    'Profile:' => 'Perfil:',
    'Profiles' => 'Perfiles',
    'Reset' => 'Limpiar',
    'Rols' => 'Roles',
    'Search' => 'Buscar',
    'Statuses' => 'Status',
    'The UI is easy to use and intuitive, just click the link below to get started' => 'La interfraz está lista para su uso, sólo pulse en el siguiente link',
    'The UI is easy to use and intuitive, just click the link below to get started.' => 'La interfraz está lista para su uso, sólo pulse en el siguiente link',
    'This is the place to manage user types.' => 'Este es el lugar para administrar los tipos de usuario.',
];
